# Generated by Django 4.1.2 on 2023-03-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micCharacterization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_PSD_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('phase_Spectrum_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('mellin_Spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('percussive_Spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('harmonic_Spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('harmonic_Prediction_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('mic_Data_Record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micCharacterization.micdatarecord')),
            ],
        ),
    ]
