# Generated by Django 4.1.2 on 2023-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectralDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectraldatabase',
            name='noise_PSD_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='spectraldatabase',
            name='overlapping_PSD_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
