# Generated by Django 4.1.2 on 2023-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectralDatabase', '0002_spectraldatabase_noise_psd_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectraldatabase',
            name='overlapping_Harmonic_PSD_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
