from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views_general, views_spectral_graphs, views_temporal_graphs, views_snr_graphs

urlpatterns = [
    path('', views_general.MicDataRecordListView.as_view(), name='mic-data-record-list'),
    path('mic-data-record/<int:pk>/', views_general.MicDataRecordDetailView.as_view(), name='mic-data-record-detail'),
    path('mic-data-record/<int:pk>/refreshed/', views_general.MicDataRecordRefreshedDetailView.as_view(), name='mic-data-record-detail-refreshed'),
    path('new/', views_general.MicDataRecordCreateView.as_view(), name='mic-data-record-create'),
    path('mic-data-record/<int:pk>/update/', views_general.MicDataRecordUpdateView.as_view(), name='mic-data-record-update'),
    path('mic-data-record/<int:pk>/delete/', views_general.MicDataRecordDeleteView.as_view(), name='mic-data-record-confirm-delete'),
    path('logs/', views_general.LogListView.as_view(), name='log-list'),
    path('logs/<int:pk>/delete/', views_general.LogDeleteView.as_view(), name='log-confirm-delete'),
    path('logs/delete/all/', views_general.delete_all_logs, name='log-confirm-delete-all'),
    path('important-concepts/', views_general.ImportantConceptsView.as_view(), name='concepts'),
    path('acoustic-propagation/', views_general.AcousticPropagationView.as_view(), name='acoustic-prop'),
    path('test/', views_general.TestView.as_view(), name='test-view'),
    
    path('original-signal-list/', views_temporal_graphs.OriginalSignalListView.as_view(), name='original-signal-list'),
    path('original-signal-list/refreshed/', views_temporal_graphs.OriginalSignalRefreshedListView.as_view(), name='original-signal-list-refreshed'),
    path('cepstrum-list/', views_temporal_graphs.CepstrumListView.as_view(), name='cepstrum-list'),
    path('cepstrum-list/refreshed/', views_temporal_graphs.CepstrumRefreshedListView.as_view(), name='cepstrum-list-refreshed'),
    path('hilbert-phase-list/', views_temporal_graphs.HilbertPhaseListView.as_view(), name='hilbert-phase-list'),
    path('hilbert-phase-list/refreshed/', views_temporal_graphs.HilbertPhaseRefreshedListView.as_view(), name='hilbert-phase-list-refreshed'),
    path('onset-strength-list/', views_temporal_graphs.OnsetStrengthListView.as_view(), name='onset-strength-list'),
    path('onset-strength-list/refreshed/', views_temporal_graphs.OnsetStrengthRefreshedListView.as_view(), name='onset-strength-list-refreshed'),
    path('autocorrelation-lag-list/', views_temporal_graphs.AutocorrelationLagListView.as_view(), name='autocorrelation-lag-list'),
    path('autocorrelation-lag-list/refreshed/', views_temporal_graphs.AutocorrelationLagRefreshedListView.as_view(), name='autocorrelation-lag-list-refreshed'),
    path('autocorrelation-bpm-list/', views_temporal_graphs.AutocorrelationBPMListView.as_view(), name='autocorrelation-bpm-list'),
    path('autocorrelation-bpm-list/refreshed/', views_temporal_graphs.AutocorrelationBPMRefreshedListView.as_view(), name='autocorrelation-bpm-list-refreshed'),
    path('autocorrelation-tempogram-list/', views_temporal_graphs.AutocorrTempogramListView.as_view(), name='autocorrelation-tempogram-list'),
    path('autocorrelation-tempogram-list/refreshed/', views_temporal_graphs.AutocorrTempogramRefreshedListView.as_view(), name='autocorrelation-tempogram-list-refreshed'),
    path('fourier-tempogram-list/', views_temporal_graphs.FourierTempogramListView.as_view(), name='fourier-tempogram-list'),
    path('fourier-tempogram-list/refreshed/', views_temporal_graphs.FourierTempogramRefreshedListView.as_view(), name='fourier-tempogram-list-refreshed'),
    
    path('pure-SNR-list/', views_snr_graphs.PureSNRListView.as_view(), name='pure-SNR-list'),
    path('pure-SNR-list/refreshed/', views_snr_graphs.PureSNRRefreshedListView.as_view(), name='pure-SNR-list-refreshed'),
    path('system-SNR-list/', views_snr_graphs.SystemSNRListView.as_view(), name='system-SNR-list'),
    path('system-SNR-list/refreshed/', views_snr_graphs.SystemSNRRefreshedListView.as_view(), name='system-SNR-list-refreshed'),
    path('signal-SNR-list/', views_snr_graphs.SignalSNRListView.as_view(), name='signal-SNR-list'),
    path('signal-SNR-list/refreshed/', views_snr_graphs.SignalSNRRefreshedListView.as_view(), name='signal-SNR-list-refreshed'),
    path('noise-SNR-list/', views_snr_graphs.NoiseSNRListView.as_view(), name='noise-SNR-list'),
    path('noise-SNR-list/refreshed/', views_snr_graphs.NoiseSNRRefreshedListView.as_view(), name='noise-SNR-list-refreshed'),
    path('avg-SNR-dist-list/', views_snr_graphs.AvgSNRDistanceListView.as_view(), name='avg-SNR-dist-list'),
    path('avg-SNR-dist-list/refreshed/', views_snr_graphs.AvgSNRDistanceRefreshedListView.as_view(), name='avg-SNR-dist-list-refreshed'),
    
    path('power-spectral-density-list/', views_spectral_graphs.PowerSpectralDensityListView.as_view(), name='power-spectral-density-list'),
    path('power-spectral-density-list/refreshed/', views_spectral_graphs.PowerSpectralDensityRefreshedListView.as_view(), name='power-spectral-density-list-refreshed'),
    path('phase-spectrum-list/', views_spectral_graphs.PhaseSpectrumListView.as_view(), name='phase-spectrum-list'),
    path('phase-spectrum-list/refreshed/', views_spectral_graphs.PhaseSpectrumRefreshedListView.as_view(), name='phase-spectrum-list-refreshed'),
    path('spectrogram-list/', views_spectral_graphs.SpectrogramListView.as_view(), name='spectrogram-list'),
    path('spectrogram-list/refreshed/', views_spectral_graphs.SpectrogramRefreshedListView.as_view(), name='spectrogram-list-refreshed'),
    path('mellin-spectrogram-list/', views_spectral_graphs.MellinListView.as_view(), name='mellin-spectrogram-list'),
    path('mellin-spectrogram-list/refreshed/', views_spectral_graphs.MellinRefreshedListView.as_view(), name='mellin-spectrogram-list-refreshed'),
    path('percussive-transform-list/', views_spectral_graphs.PercussiveComponentsListView.as_view(), name='percussive-components-list'),
    path('percussive-transform-list/refreshed/', views_spectral_graphs.PercussiveComponentsRefreshedListView.as_view(), name='percussive-components-list-refreshed'),
    path('harmonic-components-list/', views_spectral_graphs.HarmonicComponentsListView.as_view(), name='harmonic-components-list'),
    path('harmonic-components-list/refreshed/', views_spectral_graphs.HarmonicComponentsRefreshedListView.as_view(), name='harmonic-components-list-refreshed'),
    path('harmonic-prediction-list/', views_spectral_graphs.HarmonicPredictionListView.as_view(), name='harmonic-prediction-list'),
    path('harmonic-prediction-list/refreshed/', views_spectral_graphs.HarmonicPredictionRefreshedListView.as_view(), name='harmonic-prediction-list-refreshed'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)