from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from .views import (
    OriginalSignalListView,
    OnsetStrengthListView,
    AutocorrelationLagListView,
    AutocorrelationBPMListView,
    AutocorrTempogramListView,
    FourierTempogramListView,
    MellinListView,
    AveragePowerListView,
    PowerSpectrumListView,
    PercussiveComponentsListView,
    HarmonicComponentsListView,
    HarmonicTransformListView,
    ImportantConceptsView,
    MicDataRecordListView,
    MicDataRecordDetailView,
    MicDataRecordCreateView,
    MicDataRecordUpdateView,
    MicDataRecordDeleteView,
    LogListView,
    LogDeleteView,
    delete_all_logs,
)

urlpatterns = [
    path('', MicDataRecordListView.as_view(), name='mic-data-record-list'),
    path('mic-data-record/<int:pk>/', MicDataRecordDetailView.as_view(), name='mic-data-record-detail'),
    path('new/', MicDataRecordCreateView.as_view(), name='mic-data-record-create'),
    path('mic-data-record/<int:pk>/update/', MicDataRecordUpdateView.as_view(), name='mic-data-record-update'),
    path('mic-data-record/<int:pk>/delete/', MicDataRecordDeleteView.as_view(), name='mic-data-record-confirm-delete'),
    path('logs/', LogListView.as_view(), name='log-list'),
    path('logs/<int:pk>/delete/', LogDeleteView.as_view(), name='log-confirm-delete'),
    path('logs/delete/all/', delete_all_logs, name='log-confirm-delete-all'),
    path('original-signal-list/', OriginalSignalListView.as_view(), name='original-signal-list'),
    path('average-power-list/', AveragePowerListView.as_view(), name='average-power-list'),
    path('power-spectrum-list/', PowerSpectrumListView.as_view(), name='power-spectrum-list'),
    path('percussive-transform-list/', PercussiveComponentsListView.as_view(), name='percussive-components-list'),
    path('harmonic-components-list/', HarmonicComponentsListView.as_view(), name='harmonic-components-list'),
    path('harmonic-transform-list/', HarmonicTransformListView.as_view(), name='harmonic-transform-list'),
    path('important-concepts', ImportantConceptsView.as_view(), name='concepts'),
    path('onset-strength-list/', OnsetStrengthListView.as_view(), name='onset-strength-list'),
    path('autocorrelation-lag-list/', AutocorrelationLagListView.as_view(), name='autocorrelation-lag-list'),
    path('autocorrelation-bpm-list/', AutocorrelationBPMListView.as_view(), name='autocorrelation-bpm-list'),
    path('autocorrelation-tempogram-list/', AutocorrTempogramListView.as_view(), name='autocorrelation-tempogram-list'),
    path('fourier-tempogram-list/', FourierTempogramListView.as_view(), name='fourier-tempogram-list'),
    path('mellin-list/', MellinListView.as_view(), name='mellin-spectrum-list'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)