# Generated by Django 4.1.2 on 2022-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('log_Name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='MicDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_Name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('signal_File', models.FileField(upload_to='Uploads/')),
                ('signal_Start', models.IntegerField(blank=True, null=True)),
                ('reference_File', models.FileField(blank=True, upload_to='')),
                ('reference_Start', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('record_Name',),
            },
        ),
    ]
