# Generated by Django 4.1.2 on 2023-03-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('record_Name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='MicDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_Name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('prediction_Harmonics', models.IntegerField(blank=True, null=True)),
                ('noisy_Signal_File', models.FileField(blank=True, null=True, upload_to='Recordings/Original/noisy_Signal_File/')),
                ('noisy_Signal_Harmonics', models.FileField(blank=True, null=True, upload_to='Recordings/Harmonics/noisy_Signal_File/')),
                ('noisy_Signal_Percussives', models.FileField(blank=True, null=True, upload_to='Recordings/Percussives/noisy_Signal_File/')),
                ('measured_Signal_File', models.FileField(blank=True, null=True, upload_to='Recordings/Original/measured_Signal_File/')),
                ('measured_Signal_Harmonics', models.FileField(blank=True, null=True, upload_to='Recordings/Harmonics/measured_Signal_File/')),
                ('measured_Signal_Percussives', models.FileField(blank=True, null=True, upload_to='Recordings/Percussives/measured_Signal_File/')),
                ('noise_File', models.FileField(blank=True, null=True, upload_to='Recordings/Original/noise_File/')),
                ('noise_Harmonics', models.FileField(blank=True, null=True, upload_to='Recordings/Harmonics/noise_File/')),
                ('noise_Percussives', models.FileField(blank=True, null=True, upload_to='Recordings/Percussives/noise_File/')),
                ('true_Signal_File', models.FileField(blank=True, null=True, upload_to='Recordings/Original/true_Signal_File/')),
                ('true_Signal_Harmonics', models.FileField(blank=True, null=True, upload_to='Recordings/Harmonics/true_Signal_File/')),
                ('true_Signal_Percussives', models.FileField(blank=True, null=True, upload_to='Recordings/Percussives/true_Signal_File/')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
