# Generated by Django 4.1.2 on 2023-01-01 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('record_Name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='MicDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_Name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('signal_File', models.FileField(upload_to='Recordings/')),
                ('signal_Start', models.IntegerField(blank=True, null=True)),
                ('reference_File', models.FileField(blank=True, upload_to='')),
                ('reference_Start', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('prediction_Harmonics', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='TemporalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('cepstrum_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('hilbert_Phase_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('onset_Strength_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('lag_Autocorrelation_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('BPM_Autocorrelation_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('autocorrelation_Tempogram', models.CharField(default=None, max_length=1000, null=True)),
                ('fourier_Tempogram', models.CharField(default=None, max_length=1000, null=True)),
                ('mic_Data_Record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micCharacterization.micdatarecord')),
            ],
        ),
        migrations.CreateModel(
            name='SpectralDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_PSD_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('phase_Spectrum_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('mellin_Spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('percussive_Spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('harmonic_Spectrogram', models.CharField(default=None, max_length=1000, null=True)),
                ('harmonic_Prediction_Graph', models.CharField(default=None, max_length=1000, null=True)),
                ('mic_Data_Record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micCharacterization.micdatarecord')),
            ],
        ),
    ]
