# Generated by Django 4.1.2 on 2023-03-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micCharacterization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micdatarecord',
            name='reference_Noise_File',
        ),
        migrations.RemoveField(
            model_name='micdatarecord',
            name='reference_Noisy_Signal_File',
        ),
        migrations.RemoveField(
            model_name='micdatarecord',
            name='reference_Signal_File',
        ),
    ]
