# Generated by Django 4.1.2 on 2022-11-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micCharacterization', '0002_micdatarecord_hop_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micdatarecord',
            name='hop_Length',
        ),
    ]
