# Generated by Django 4.1.2 on 2023-03-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('micCharacterization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mic_Data_Record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micCharacterization.micdatarecord')),
            ],
        ),
    ]
