# Generated by Django 4.1.2 on 2023-03-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticaldatabase',
            old_name='overlapping_PDF_Graph',
            new_name='original_PDF_Graph',
        ),
    ]
