# Generated by Django 4.1.2 on 2023-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='gaussian_Kernel_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
