# Generated by Django 4.1.2 on 2023-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0002_rename_overlapping_pdf_graph_statisticaldatabase_original_pdf_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='harmonic_HPSS_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statisticaldatabase',
            name='percussive_HPSS_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
