# Generated by Django 4.1.2 on 2023-03-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0002_statisticaldatabase_gaussian_kernel_pdf_graph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticaldatabase',
            old_name='gaussian_Kernel_PDF_Graph',
            new_name='kernel_Function_PDF_Graph',
        ),
    ]
