# Generated by Django 4.1.2 on 2023-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0003_statisticaldatabase_harmonic_hpss_pdf_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='welch_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
