# Generated by Django 4.1.2 on 2023-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0003_rename_gaussian_kernel_pdf_graph_statisticaldatabase_kernel_function_pdf_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='spectrogram_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
