# Generated by Django 4.1.2 on 2023-03-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0004_statisticaldatabase_welch_pdf_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='magnitude_FFT_Spectrum_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statisticaldatabase',
            name='magnitude_FFT_Time_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statisticaldatabase',
            name='phase_FFT_Spectrum_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statisticaldatabase',
            name='phase_FFT_Time_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
