# Generated by Django 4.1.2 on 2023-03-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0005_statisticaldatabase_harmonic_spectrogram_pdf_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='autocorrelation_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statisticaldatabase',
            name='lag_Autocorrelation_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
