# Generated by Django 4.1.2 on 2023-03-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticalDatabase', '0009_statisticaldatabase_inst_phase_pdf_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticaldatabase',
            name='signal_Inversion_PDF_Graph',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
